//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aausers
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> aereo { get; set; }
        public Nullable<bool> marino { get; set; }
    }
}
