//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_AdminEntities : DbContext
    {
        public db_AdminEntities()
            : base("name=db_AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aausers> aausers { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<direcciones> direcciones { get; set; }
        public DbSet<usuarios_manifiesto_menu> usuarios_manifiesto_menu { get; set; }
    }
}
