//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.direcciones = new HashSet<direcciones>();
        }
    
        public long id_cliente { get; set; }
        public string codigo_tributario { get; set; }
        public string nombre_cliente { get; set; }
        public string nombre_facturar { get; set; }
        public Nullable<long> id_vendedor { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_cobrador { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<bool> es_consigneer { get; set; }
        public Nullable<bool> es_shipper { get; set; }
        public Nullable<int> id_frecuencia { get; set; }
        public Nullable<int> id_credito { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<double> hora_creacion { get; set; }
        public string id_clase { get; set; }
        public Nullable<long> id_anterior { get; set; }
        public Nullable<long> id_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_uvisita { get; set; }
        public string usr { get; set; }
        public string pwd { get; set; }
        public Nullable<long> id_sales_support { get; set; }
        public Nullable<System.DateTime> ultima_fecha_descarga { get; set; }
        public Nullable<int> encuesta_id { get; set; }
        public Nullable<int> encuesta { get; set; }
        public string id_pais { get; set; }
        public Nullable<short> id_regimen { get; set; }
        public string codigo_tributario2 { get; set; }
        public string observacion { get; set; }
        public Nullable<long> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<long> ultimo_tipo_movimiento { get; set; }
        public Nullable<bool> ultimo_movimiento_asegurado { get; set; }
        public Nullable<int> requiere_rubro_alias { get; set; }
        public Nullable<long> id_vendedor_grh { get; set; }
        public Nullable<long> id_sales_support_grh { get; set; }
        public string ref_interna_pricing { get; set; }
        public Nullable<bool> con_cotizacion { get; set; }
        public Nullable<int> marca { get; set; }
        public string email { get; set; }
        public Nullable<bool> es_coloader { get; set; }
        public Nullable<bool> incluir_saldo { get; set; }
    
        public virtual ICollection<direcciones> direcciones { get; set; }
    }
}
