using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace db_aereo.Entities.Entities
{
    [Table("Carriers")]
    public class carriers
    {
        [Key]
        public double CarrierID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double CreatedTime { get; set; }
        public double Expired { get; set; }
        public string CarrierCode { get; set; }
        public double ver_AWBNumber { get; set; }
        public double hor_AWBNumber { get; set; }
        public double ver_AccountShipperNo { get; set; }
        public double hor_AccountShipperNo { get; set; }
        public double ver_ShipperData { get; set; }
        public double hor_ShipperData { get; set; }
        public double ver_AccountConsignerNo { get; set; }
        public double hor_AccountConsignerNo { get; set; }
        public double ver_ConsignerData { get; set; }
        public double hor_ConsignerData { get; set; }
        public double ver_AgentData { get; set; }
        public double hor_AgentData { get; set; }
        public double ver_AccountInformation { get; set; }
        public double hor_AccountInformation { get; set; }
        public double ver_IATANo { get; set; }
        public double hor_IATANo { get; set; }
        public double ver_AccountAgentNo { get; set; }
        public double hor_AccountAgentNo { get; set; }
        public double ver_AirportDepID { get; set; }
        public double hor_AirportDepID { get; set; }
        public double ver_RequestedRouting { get; set; }
        public double hor_RequestedRouting { get; set; }
        public double ver_AirportToCode1 { get; set; }
        public double hor_AirportToCode1 { get; set; }
        public double ver_CarrierID { get; set; }
        public double hor_CarrierID { get; set; }
        public double ver_AirportToCode2 { get; set; }
        public double hor_AirportToCode2 { get; set; }
        public double ver_AirportToCode3 { get; set; }
        public double hor_AirportToCode3 { get; set; }
        public double ver_CarrierCode2 { get; set; }
        public double hor_CarrierCode2 { get; set; }
        public double ver_CarrierCode3 { get; set; }
        public double hor_CarrierCode3 { get; set; }
        public double ver_CurrencyID { get; set; }
        public double hor_CurrencyID { get; set; }
        public double ver_ChargeType { get; set; }
        public double hor_ChargeType { get; set; }
        public double ver_ValChargeType { get; set; }
        public double hor_ValChargeType { get; set; }
        public double ver_OtherChargeType { get; set; }
        public double hor_OtherChargeType { get; set; }
        public double ver_DeclaredValue { get; set; }
        public double hor_DeclaredValue { get; set; }
        public double ver_AduanaValue { get; set; }
        public double hor_AduanaValue { get; set; }
        public double ver_AirportDesID { get; set; }
        public double hor_AirportDesID { get; set; }
        public double ver_FlightDate1 { get; set; }
        public double hor_FlightDate1 { get; set; }
        public double ver_FlightDate2 { get; set; }
        public double hor_FlightDate2 { get; set; }
        public double ver_SecuredValue { get; set; }
        public double hor_SecuredValue { get; set; }
        public double ver_HandlingInformation { get; set; }
        public double hor_HandlingInformation { get; set; }
        public double ver_Observations { get; set; }
        public double hor_Observations { get; set; }
        public double ver_NoOfPieces { get; set; }
        public double hor_NoOfPieces { get; set; }
        public double ver_Weights { get; set; }
        public double hor_Weights { get; set; }
        public double ver_WeightsSymbol { get; set; }
        public double hor_WeightsSymbol { get; set; }
        public double ver_Commodities { get; set; }
        public double hor_Commodities { get; set; }
        public double ver_ChargeableWeights { get; set; }
        public double hor_ChargeableWeights { get; set; }
        public double ver_CarrierRates { get; set; }
        public double hor_CarrierRates { get; set; }
        public double ver_CarriersubTot { get; set; }
        public double hor_CarriersubTot { get; set; }
        public double ver_NatureQtyGoods { get; set; }
        public double hor_NatureQtyGoods { get; set; }
        public double ver_TotNoOfPieces { get; set; }
        public double hor_TotNoOfPieces { get; set; }
        public double ver_TotWeight { get; set; }
        public double hor_TotWeight { get; set; }
        public double ver_TotCarrierRate { get; set; }
        public double hor_TotCarrierRate { get; set; }
        public double ver_TotChargeWeightPrepaid { get; set; }
        public double hor_TotChargeWeightPrepaid { get; set; }
        public double ver_TotChargeWeightCollect { get; set; }
        public double hor_TotChargeWeightCollect { get; set; }
        public double ver_TotChargeValuePrepaid { get; set; }
        public double hor_TotChargeValuePrepaid { get; set; }
        public double ver_TotChargeValueCollect { get; set; }
        public double hor_TotChargeValueCollect { get; set; }
        public double ver_TotChargeTaxPrepaid { get; set; }
        public double hor_TotChargeTaxPrepaid { get; set; }
        public double ver_TotChargeTaxCollect { get; set; }
        public double hor_TotChargeTaxCollect { get; set; }
        public double ver_AnotherChargesAgentPrepaid { get; set; }
        public double hor_AnotherChargesAgentPrepaid { get; set; }
        public double ver_AnotherChargesAgentCollect { get; set; }
        public double hor_AnotherChargesAgentCollect { get; set; }
        public double ver_AnotherChargesCarrierPrepaid { get; set; }
        public double hor_AnotherChargesCarrierPrepaid { get; set; }
        public double ver_AnotherChargesCarrierCollect { get; set; }
        public double hor_AnotherChargesCarrierCollect { get; set; }
        public double ver_TotPrepaid { get; set; }
        public double hor_TotPrepaid { get; set; }
        public double ver_TotCollect { get; set; }
        public double hor_TotCollect { get; set; }
        public double ver_TerminalFee { get; set; }
        public double hor_TerminalFee { get; set; }
        public double ver_CustomFee { get; set; }
        public double hor_CustomFee { get; set; }
        public double ver_FuelSurcharge { get; set; }
        public double hor_FuelSurcharge { get; set; }
        public double ver_SecurityFee { get; set; }
        public double hor_SecurityFee { get; set; }
        public double ver_PBA { get; set; }
        public double hor_PBA { get; set; }
        public double ver_TAX { get; set; }
        public double hor_TAX { get; set; }
        public double ver_AdditionalChargeName1 { get; set; }
        public double hor_AdditionalChargeName1 { get; set; }
        public double ver_AdditionalChargeVal1 { get; set; }
        public double hor_AdditionalChargeVal1 { get; set; }
        public double ver_AdditionalChargeName2 { get; set; }
        public double hor_AdditionalChargeName2 { get; set; }
        public double ver_AdditionalChargeVal2 { get; set; }
        public double hor_AdditionalChargeVal2 { get; set; }
        public double ver_Invoice { get; set; }
        public double hor_Invoice { get; set; }
        public double ver_ExportLic { get; set; }
        public double hor_ExportLic { get; set; }
        public double ver_AgentContactSignature { get; set; }
        public double hor_AgentContactSignature { get; set; }
        public double ver_Instructions { get; set; }
        public double hor_Instructions { get; set; }
        public double ver_AgentSignature { get; set; }
        public double hor_AgentSignature { get; set; }
        public double ver_AWBDate { get; set; }
        public double hor_AWBDate { get; set; }
        public double ver_AirportCode { get; set; }
        public double hor_AirportCode { get; set; }
        public double ver_AdditionalChargeName3 { get; set; }
        public double hor_AdditionalChargeName3 { get; set; }
        public double ver_AdditionalChargeVal3 { get; set; }
        public double hor_AdditionalChargeVal3 { get; set; }
        public double ver_AdditionalChargeName4 { get; set; }
        public double hor_AdditionalChargeName4 { get; set; }
        public double ver_AdditionalChargeVal4 { get; set; }
        public double hor_AdditionalChargeVal4 { get; set; }
        public string Countries { get; set; }
        public double ver_ChargeType2 { get; set; }
        public double hor_ChargeType2 { get; set; }
        public double ver_ValChargeType2 { get; set; }
        public double hor_ValChargeType2 { get; set; }
        public double ver_OtherChargeType2 { get; set; }
        public double hor_OtherChargeType2 { get; set; }
        public double OtherChargesPrintType { get; set; }
        public double ComisionRate { get; set; }
        public double GroupID { get; set; }
        public double ver_AWBNumber2 { get; set; }
        public double hor_AWBNumber2 { get; set; }
        public double ver_AWBNumber3 { get; set; }
        public double hor_AWBNumber3 { get; set; }
    }
}
